### PR TITLE
Error in WebPack build #49

### PR DESCRIPTION
**Pull request by jhwegener**
This PullRequest fixes the issues I had with CSS Files mentioned in https://github.com/gonzofish/angular-librarian/issues/49

### CODE REVIEW

**Comment by gonzofish** [comment]
Hey, thanks for the pull request--I'll give it a look within the next couple of days. I've been on vacation and I'm getting back into the rhythm normal life.

**Comment by gonzofish** [comment]
I'm merging this in for now, but I want to make sure there are no cases being skipped. When I moved everything to working from a common webpack base, I excluded the previous ExtractTextPlugin usage...I just want to make sure that this pull request & the previous functionality are in sync.

@jhwegener thanks again for the pull request! Always nice to have people contributing!

**Comment by jhwegener** [comment]
@gonzofish you're welcome ;)

**Comment by gonzofish** [comment]
Just a heads up, from the looks of this it should be good and will be in the next release (today). I forgot that I had moved the actuall `ExtractTextPlugin.extract` into the `buildRules` method of `webpack/webpack.utils.js`.

A little more testing and I'll be confident that everything's working as expected.

**Pull request merged**
