### PR TITLE
Feature/add tslint prefix

### PR DESCRIPTION
**Pull request by jensbodal**
I thought it would be useful to set the library prefix when creating a new library.  Setting the prefix is an important part of creating libraries so that you can avoid collisions. 

I had some trouble with adding unit tests for the selector.  I tested the generation in a sample repo and the component test properly validates the selector, but I couldn't figure it out for the directive test.

Also there was a bug I fixed.  If you create a directive without a name it defaults to `asdf`.  It appears using `name` as the value for the `name` argument was causing an issue, so I changed it to `directiveName`. 

```
# in an example app... 
name="my-selector"; 
rm -rf src/directives; ./node_modules/angular-librarian/bin/index.js d ; 
vim src/directives/$name.directive.ts
# enter my-selector as the name
```

### CODE REVIEW

**Comment by gonzofish** [comment]
Thanks for the PR, I'll give it a look soon!

**Comment by gonzofish** [comment]
Oh, and great catch on the empty directive name--I had noticed that and missed fixing it

**Comment by gonzofish** [comment]
Something I'm confused about here, why can't I just set the selector name to `my-selector`? What's the added bonus of answering the prefix separate from the selector?

**Comment by jensbodal** [comment]
Just to make sure we're on the same page, the prefix answer is only when setting up the library, it sets the linting enforced prefix in both components and directives. 

Afterwards the generating of a component/directive works the same way as it does with the angular-cli.  When you do `ng g my-component`, it reads the `prefix` value from the `.angular-cli.json` and prefixes the selector when generating the component.

E.g.

```
# .angular-cli.json has value "apps": [ { "prefix": "ngfl" } ]
ng g component myComponent
# create src/app/my-component/my-component.component.ts
# component has value selector: 'ngfl-my-component',

**Comment by jensbodal** [comment]
Just to make sure we're on the same page, the prefix answer is only when setting up the library, it sets the linting enforced prefix in both components and directives. 

Afterwards the generating of a component/directive works the same way as it does with the angular-cli.  When you do `ng g my-component`, it reads the `prefix` value from the `.angular-cli.json` and prefixes the selector when generating the component.

E.g.

```
# .angular-cli.json has value "apps": [ { "prefix": "ngfl" } ]
ng g component myComponent
# create src/app/my-component/my-component.component.ts
# component has value selector: 'ngfl-my-component',

**Comment by jensbodal** [comment]
Just to make sure we're on the same page, the prefix answer is only when setting up the library, it sets the linting enforced prefix in both components and directives. 

Afterwards the generating of a component/directive works the same way as it does with the angular-cli.  When you do `ng g my-component`, it reads the `prefix` value from the `.angular-cli.json` and prefixes the selector when generating the component.

E.g.

```
# .angular-cli.json has value "apps": [ { "prefix": "ngfl" } ]
ng g component myComponent
# create src/app/my-component/my-component.component.ts
# component has value selector: 'ngfl-my-component',
```

**Comment by jensbodal** [comment]
Just to make sure we're on the same page, the prefix answer is only when setting up the library, it sets the linting enforced prefix in both components and directives. 

Afterwards the generating of a component/directive works the same way as it does with the angular-cli.  When you do `ng g my-component`, it reads the `prefix` value from the `.angular-cli.json` and prefixes the selector when generating the component.

E.g.

```
# .angular-cli.json has value "apps": [ { "prefix": "ngfl" } ]
ng g component myComponent
# create src/app/my-component/my-component.component.ts
# component has value selector: 'ngfl-my-component',
```

**Comment by gonzofish** [comment]
Ahhhh, I see what you did. Nice! I especially like leveraging the value inside the `tslint.json file to accomplish the work...

Another question: what happens if they don't want to use a prefix? I'm just not sure how the `tslint.json` rules behave with empty prefix strings. 

Real nice work!

**Comment by jensbodal** [comment]
I allowed empty strings, and it will set the empty string for the prefix.  If there's no prefix it simply won't add it to to the selector.  Thanks :)

**Comment by gonzofish** [comment]
Ok, great, that's what I thought I was reading, just wanted to verify. Looks good!

**Comment by jensbodal** [comment]
Thanks :)

Nice work btw. Angular Package Format is confusing and this looks really promising, likely going to be using this for our libraries.

**Comment by gonzofish** [comment]
Awesome! Anything I can do to help, let me know.

**Pull request merged**
